using System;
using System.IO;
using System.Threading.Tasks;
using BigSort.Common;
using BigSort.V2;
using BigSort.Validation;
using McMaster.Extensions.CommandLineUtils;
using Microsoft.Extensions.Logging;

namespace BigSort.Commands
{
  /// <summary>
  /// The check command.
  /// </summary>
  [Command(Name = "check", Description = @"The command performs simple check to ensure that the output file is correct.
Basically it just reads the output file generated by the merge-sort command and ensures that all lines are in the sorted order (the increasing sequence)
")]
  internal class CommandCheck
  {
    public async Task OnExecuteAsync()
    {
      var inFilePath = @"C:\_sorting\out.txt";
      var inFileSize = new FileInfo(inFilePath).Length;

      var loggerFactory = LoggerFactory.Create(builder =>
      {
        builder
        .AddConsole()
        .SetMinimumLevel(LogLevel.Debug);
      });
      var logger = loggerFactory.CreateLogger(nameof(CommandCheck));

      try
      {
        var context = new PipelineContext(loggerFactory);
        var sourceReader = new SourceReader();
        var checkOrderBlock = CheckOrderBlock.Create(inFileSize);

        var readerTask = sourceReader.StartAsync(inFilePath, 10000, context, checkOrderBlock);
        await Task.WhenAll(checkOrderBlock.Completion, readerTask);

        logger.LogInformation("The file is valid.");
      }
      catch(Exception e)
      {
        logger.LogCritical(e, "The validation has been faulted");
      }
      finally
      {
      }
    }
  }
}
